### ISSUE TITLE
Request for change

### ISSUE THREAD

**Issue by oldblackcrow** [alankrantas/micropython-TEA5767#1]
Hello. I am wondering if this can be ported to CircuitPython. So far, the only issue I'm having is with the machine library. I can't find it anywhere and I'm using a PyPortal Pynt, so assumed I can just change out the machine for board. Guess not... Is this something that can be done? Thanks!

**Comment by alankrantas** [comment]
[Here](https://github.com/alankrantas/circuitpython-TEA5767).

Tested on RPi Pico. I think it should work on all CircuitPython devices but I'll do more test later (I have a Metro M4, a ItsyBitsy M0 and an ESP32-S2). The driver itself is essentially identical.
