### ISSUE TITLE
Auto searching function seems not working when it playback on a strong signal

### ISSUE THREAD

**Issue by swanduron** [alankrantas/micropython-TEA5767#2]
Hello contributor,

I appreciate your woring on micropython project with TEA5767 module. The lib works good in most cases, but there is only one issue that needs your time to have a glimpse on it.

For example, the module now is playback on a strong signal that the ADC level=5. In this case, if I input `radio.search(True, dir=0, adc=5)`  to search next radio station, the module will lock current station until I use `radio.search(True, dir=0, adc=0)`  to implement next frequency and then the command `radio.search(True, dir=0, adc=5)` runs as expectation to lock the next strong station.

I would like to know this is the corner case for this lib or my mistake operation?

**Comment by alankrantas** [comment]
> If the search mode is enabled, the radio would attempt to find a station with strong signal whenever you set a new frequency.

```radio.search()``` only turns on/off search **mode**. You have to use ```radio.change_freqency()``` or ```radio.set_frequency()``` to force it to find a new possible frequency.

**Comment by swanduron** [comment]
Got it! The radio will auto search the next available (match the ADC threshold) station when `radio.change_freqency(±0.1)` follows `radio.search(True)`. 

Great job buddy!

**Comment by swanduron** [comment]
An additional request. I am fighting with the SI4703 radio module on the Micropython platform but have been no progress. Can I request you a repo for that chip?

**Comment by alankrantas** [comment]
I'm afraid I don't have one right now and ordering one might take a long time due to the COVID lock-down in China.

**Comment by swanduron** [comment]
I asked Taobao's story, and they said they could dispatch SF express but BOA. You can assign the bill (both on Taobao and SFexpress) to me and I will pay it. My Taobao account: `swanduron` and the hyperlink is `https://detail.tmall.com/item.htm?spm=a230r.1.14.12.1dbd2e4bv3tBzp&id=658475826440&ns=1&abbucket=3`

It just depends on your time and interest, I don't expect that you are stuck in mess troubles. ToT
